version: '3'

services:

  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: gofila-api
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
  
  # db:
  #   build: .docker/postgres
  #   container_name: gofila-db
  #   restart: always
  #   tty: true
  #   volumes:
  #     - .docker/dbdata:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  postgres:
    image: postgres:12
    container_name: gofila-db
    tty: true
    restart: always
    volumes:
    - .docker/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-alpha.9
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: 0yqHXEShvwzj

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:80"
    depends_on:
      - postgres
volumes:
  db_data:
